- name: Install snap with option --classic
  snap:
    name: certbot
    classic: yes

- name: Install and Create Certbot certificate
  command: certbot --nginx -d {{ hostname }}.brimore.com -m salahkhaled.eng@gmail.com -n --agree-tos
  ignore_errors: yes

  #- name: Install and Create Certbot certificate second try
  #command: certbot --nginx -d {{ hostname }}.brimore.com -n
  #ignore_errors: yes

- name: Restart nginx service
  systemd:
     name: nginx
     enabled: yes
     state: restarted
